var elizabethDict = {
    "'t": "it",
    ".": " periodT.",
    "dash'd": "torn",
    "drowning-mark": "",
    "has't": "have",
    "hath't": "have",
    "hence-forth": "from now on",
    "o'": "on",
    "o’er": "over",
    "th'": "the",
    "welkin's": "skies",
    "wi'": "with",
    "wid'st": "wut is",
    "wide-chop": "fat mouth",
    "wide-chopped": "fat mouthed",
    "heard'st": "heard",
    "th'": "the",
    "th’": "the",
    hearts: "gamer boys",
    abhor: "reject",
    absolute: "pristine",
    addiction: "tendancy",
    ahold: "close to the wind",
    allay: "stop",
    alright: "bet",
    amazement: "poggers",
    art: "r",
    bad: "trash",
    balk: "hesitate",
    beest: "be",
    bestir: "go",
    brave: "solid",
    byn: "been",
    character: "word",
    cheerely: "lessgo",
    cheerly: "lessgo",
    coil: "trouble",
    complexion: "appearance",
    couch: "sleep",
    cunning: "smart af",
    cur: "mut",
    dashes: "put",
    delation: "accusation",
    deserving: "brownie point",
    doth: "do",
    doth: "does",
    draw: "call to",
    egal: "equal",
    emboss: "stalk",
    ere: "before",
    excellent: "dank",
    expedience: "quick",
    fain: "gladly",
    fall: "do",
    fancy: "have a crush on",
    fear: "shook",
    fraughting: "",
    front: "object",
    furlongs: "mile",
    furlongs: "miles",
    furze: "plant",
    gape: "",
    gast: "shook",
    glisters: "glitters",
    glut: "swallow",
    gorse: "plant",
    hap: "happens",
    hast: "has",
    hath: "has",
    heath: "land",
    heigh: "listen",
    heigh: "listen",
    hence: "so",
    killeth: "kill",
    knocke: "knock",
    loss: "L",
    mad: "wack",
    mar: "foobar",
    methinks: "I think",
    mightst: "might",
    mine: "my",
    muschance: "bad luck",
    naught: "not",
    nay: "no",
    o: "oh",
    oft: "often",
    ok: "bet",
    painful: "cringe",
    perished: "died",
    pitch: "black goo",
    quake: "am shakin in my boots",
    rags: "cheugy ass rags",
    retire: "get some Z's",
    roarer: "wave",
    roarers: "waves",
    shalt: "shall",
    small: "smol",
    thee: "u",
    thine: "ur",
    thou: "u",
    thy: "ur",
    unto: "to",
    vile: "trash",
    wanteth: "want",
    wanteth: "want",
    welkin: "sky",
    wend: "go",
    wert: "were",
    wherefore: "y",
    whom: "who",
    whoreson: "dickhead",
    wilt: "will",
    win: "w",
    worke: "work",
    wow: "pog",
    yare: "quick",
    yarely: "quickly",
    zany: "extra",
    perdition: "L",
    betid: "happen",
    sawst: "saw",
    bootless: "useless",
    inquisition: "question",
    stay: "hol up",
    ope: "open",
    tend: "subscribe",
    tended: "subscribed to",
    abysm: "vortex",
    aught: "anything",
    "rememb'rest": "remember",
    "cam'st": "came",
    remembrest: "remember",
    camst: "came",
    mayst: "may",
    virtue: "G.O.A.T",
    wast: "was",
    issued: "born",
    teen: "trauma",
    mark: "pay attention to",
    perfidious: "toxic",
    signory: "state",
    signories: "states",
    primte: "main character",
    heedfully: "attentively",
    valourous: "beautiful",
    morrow: "morning",
    morn: "morning"
};

export function getShakesWord(name) {
    return elizabethDict[name];
}