var elizabethDict = {
    "'t": "it",
    ".": " preiodT.",
    "drowning-mark": "",
    "has't": "have",
    "hath't": "have",
    "hence-forth": "from now on",
    "o'": "on",
    "o’er": "over",
    "th'": "the",
    "welkin's": "skies",
    "wi'": "with",
    "wid'st": "wut is",
    "wide-chop": "fat mouth",
    "wide-chopped": "fat mouthed",
    abhor: "reject",
    absolute: "pristine",
    addiction: "tendancy",
    ahold: "close to the wind",
    allay: "stop",
    alright: "bet",
    art: "r",
    balk: "hesitate",
    beest: "be",
    bestir: "go",
    brave: "solid",
    character: "word",
    cheerly: "*screams cutely*",
    coil: "trouble",
    complexion: "appearance",
    couch: "sleep",
    cunning: "smart af",
    cur: "mut",
    dashes: "put",
    delation: "accusation",
    deserving: "brownie point",
    doth: "do",
    doth: "does",
    draw: "call to",
    egal: "equal",
    emboss: "stalk",
    expedience: "quick",
    fain: "gladly",
    fall: "do",
    fancy: "have a crush on",
    fear: "shook",
    front: "object",
    furze: "plant",
    gape: "",
    gast: "shook",
    glisters: "glitters",
    glut: "swallow",
    gorse: "plant",
    hap: "happens",
    hast: "has",
    hath: "has",
    heath: "land",
    heigh: "listen",
    hence: "so",
    killeth: "kill",
    mad: "wack",
    mar: "foobar",
    methinks: "I think",
    mightst: "might",
    mine: "my",
    muschance: "bad luck",
    nay: "no",
    o: "oh",
    oft: "often",
    ok: "bet",
    painful: "cringe",
    pitch: "black goo",
    quake: "am shakin in my boots",
    retire: "get some Z's",
    roarer: "wave",
    roarers: "waves",
    shalt: "shall",
    small: "smol",
    thee: "u",
    thine: "ur",
    thou: "u",
    thy: "ur",
    unto: "to",
    wanteth: "want",
    wanteth: "want",
    welkin: "sky",
    wend: "go",
    wert: "were",
    wherefore: "y",
    whom: "who",
    whoreson: "dickhead",
    wilt: "will",
    worke: "work",
    yare: "quick",
    yarely: "quickly",
    zany: "extra",
    perished: "died",
    ere: "before",
    fraughting: "",
    knocke: "knock",
    "dash'd": "torn",
    byn: "been",
};

var elizabethPhraseDict = {
    "your art": "your trickery"
};

export function getShakesWord(name) {
    return elizabethDict[name];
}